package swing_box;

import java.awt.Point;
import java.util.Random;

public class JBoxFrame extends javax.swing.JFrame {

    private static final int STEP = 3;
    private int kx, ky;
    private MoveThread thread;

    /**
     * Creates new form JBoxFrame
     */
    public JBoxFrame() {
        initComponents();
        kx = ky = 1;

        Random random = new Random();
        jPanelTop.setLayout(null);
        jBox.setLocation(random.nextInt(jPanelTop.getWidth() - jBox.getWidth()),
                random.nextInt(jPanelTop.getHeight() - jBox.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBottom = new javax.swing.JPanel();
        jStartBtn = new javax.swing.JButton();
        jExitBtn = new javax.swing.JButton();
        jStopBtn = new javax.swing.JButton();
        jPanelTop = new javax.swing.JPanel();
        jBox = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBottom.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jStartBtn.setBackground(new java.awt.Color(255, 102, 102));
        jStartBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jStartBtn.setText("Start");
        jStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartMove(evt);
            }
        });

        jExitBtn.setBackground(new java.awt.Color(255, 102, 102));
        jExitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jExitBtn.setText("Exit");
        jExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExit(evt);
            }
        });

        jStopBtn.setBackground(new java.awt.Color(255, 102, 102));
        jStopBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jStopBtn.setText("Stop");
        jStopBtn.setEnabled(false);
        jStopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStopMove(evt);
            }
        });

        javax.swing.GroupLayout jPanelBottomLayout = new javax.swing.GroupLayout(jPanelBottom);
        jPanelBottom.setLayout(jPanelBottomLayout);
        jPanelBottomLayout.setHorizontalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addComponent(jExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBottomLayout.setVerticalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStartBtn)
                    .addComponent(jStopBtn)
                    .addComponent(jExitBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBox.setBackground(new java.awt.Color(255, 102, 102));
        jBox.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jBoxLayout = new javax.swing.GroupLayout(jBox);
        jBox.setLayout(jBoxLayout);
        jBoxLayout.setHorizontalGroup(
            jBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jBoxLayout.setVerticalGroup(
            jBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStartMove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartMove
        thread = new MoveThread(this, 10);
        thread.start();
        switchButtons();
    }//GEN-LAST:event_jStartMove

    private void jStopMove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStopMove
        thread.stop();
        switchButtons();
    }//GEN-LAST:event_jStopMove

    private void switchButtons() {
        jStartBtn.setEnabled(!jStartBtn.isEnabled());
        jStopBtn.setEnabled(!jStopBtn.isEnabled());
    }
    
    private void jExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExit
        thread.stop();
        this.dispose();
    }//GEN-LAST:event_jExit

    //* 1 step of animation
    public void moveBox() {
        Point p = jBox.getLocation();
        
        if ( (p.x >= jPanelTop.getWidth() - jBox.getWidth()) || (p.x <= 0) ) {
            kx = -kx;
        }
        
        if ( (p.y >= jPanelTop.getHeight() - jBox.getHeight()) || (p.y <= 0) ) {
            ky = -ky;
        }
        
        p.move(p.x + kx * STEP,
               p.y + ky * STEP);
        jBox.setLocation(p);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JBoxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JBoxFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBox;
    private javax.swing.JButton jExitBtn;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JButton jStartBtn;
    private javax.swing.JButton jStopBtn;
    // End of variables declaration//GEN-END:variables
}
